; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
monitor_filters = esp32_exception_decoder
extra_scripts = build.py
framework = arduino
lib_deps = 
	https://github.com/tzapu/WiFiManager.git@2.0.17 ; +sha.b67b782
	https://github.com/ESP32Async/ESPAsyncWebServer.git ;@3.7.4
	https://github.com/madhephaestus/ESP32Servo.git@3.0.6+sha.e697ea7
	https://github.com/adafruit/Adafruit_SSD1306.git ; @2.5.13+sha.78d6a13
	waspinator/AccelStepper@^1.64
	bblanchon/ArduinoJson@5.13.4

[env:native]
platform = native
test_ignore = test_embedded
; test_build_src = false
build_src_filter =
	+<movement.cpp>
test_filter =
    native/**